# Generated by Django 4.2.7 on 2024-01-01 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "data_name",
                    models.CharField(max_length=50, unique=True, verbose_name="资料名称"),
                ),
            ],
            options={
                "db_table": "draw_data",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "sensor_name",
                    models.CharField(max_length=50, unique=True, verbose_name="传感器名称"),
                ),
            ],
            options={
                "db_table": "draw_sensor",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "project_name",
                    models.CharField(max_length=50, unique=True, verbose_name="项目名称"),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="drawing.sensor",
                        verbose_name="所属传感器",
                    ),
                ),
            ],
            options={
                "db_table": "draw_project",
            },
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("material_code", models.CharField(max_length=50, verbose_name="物料编号")),
                ("drawing_name", models.CharField(max_length=50, verbose_name="材料名称")),
                (
                    "drawing_spec",
                    models.CharField(max_length=50, verbose_name="规格/图纸号"),
                ),
                ("drawing_page", models.CharField(max_length=50, verbose_name="图纸页数")),
                (
                    "drawing_client_id",
                    models.CharField(max_length=50, verbose_name="客户编号"),
                ),
                (
                    "drawing_version",
                    models.CharField(max_length=50, verbose_name="版本号"),
                ),
                ("drawing_remark", models.CharField(max_length=100, verbose_name="备注")),
                ("drawing_url", models.CharField(max_length=100, verbose_name="地址")),
                ("is_deleted", models.IntegerField(default=0, verbose_name="逻辑删除0否1是")),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="drawing.data",
                        verbose_name="所属资料",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="drawing.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="drawing.sensor",
                        verbose_name="所属传感器",
                    ),
                ),
            ],
            options={
                "db_table": "draw_drawing",
            },
        ),
        migrations.AddField(
            model_name="data",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="drawing.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="drawing.sensor",
                verbose_name="所属传感器",
            ),
        ),
    ]
